config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :sale_types
  resources :price_entries
  resources :distributors
  resources :sub_categories
  resources :packages
  resources :units
  resources :categories
  resources :products
  resources :suppliers


  root to: 'products#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
	has_many :sub_categories, dependent: :destroy
end

app/models/distributor.rb
class Distributor < ApplicationRecord

	has_many :price_entries, dependent: :destroy
	
end

app/models/package.rb
class Package < ApplicationRecord

	belongs_to :product
	belongs_to :unit

	has_many :price_entries, dependent: :destroy

end

app/models/price_entry.rb
class PriceEntry < ApplicationRecord

	belongs_to :distributor
	belongs_to :package
	belongs_to :sale_type
	belongs_to :user


end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :supplier
	belongs_to :category 
	belongs_to :sub_category 

	has_many :packages, dependent: :destroy

	validates :name, uniqueness: { case_sensitive: false}
	validates :name, presence: true

	validates :category_id, presence: true
	validates :sub_category_id, presence: true


	
end

app/models/sale_type.rb
class SaleType < ApplicationRecord
	has_many :price_entries, dependent: :destroy

end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
	has_many :products, dependent: :destroy

	belongs_to :category
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :products, dependent: :destroy

	validates :name, uniqueness: { case_sensitive: false}
	validates :name, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
	has_many :packages , dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :price_entries
end

app/controllers/price_entries_controller.rb
class PriceEntriesController < ApplicationController
  before_action :set_price_entry, only: [:show, :edit, :update, :destroy]
  before_action :set_footer

  # GET /price_entries
  # GET /price_entries.json
  def index
    @price_entries = PriceEntry.all
  end

  # GET /price_entries/1
  # GET /price_entries/1.json
  def show
  end

  # GET /price_entries/new
  def new
    @price_entry = PriceEntry.new
  #  @package = Package.all.map { |i| [i.product.name, i.id]}
    @package = Package.all.map do |i| 
      str = i.product.name + "/" + i.pkgsize.to_s + "/" + i.size.to_s + "/" + i.unit.name
      [str, i.id]
    end 

    @sale_type = SaleType.all.map { |i| [i.name, i.id]}
    @distributor = Distributor.all.map { |i| [i.name, i.id]}

  end

  # GET /price_entries/1/edit
  def edit
    @package = Package.all.map { |i| [i.product.name, i.id]}
    @distributor = Distributor.all.map { |i| [i.name, i.id]}
    @sale_type = SaleType.all.map { |i| [i.name, i.id]}

  end

  # POST /price_entries
  # POST /price_entries.json
  def create
    @price_entry = PriceEntry.new(price_entry_params)
    @price_entry.user = current_user

    respond_to do |format|
      if @price_entry.save
        format.html { redirect_to @price_entry, notice: 'Price entry was successfully created.' }
        format.json { render :show, status: :created, location: @price_entry }
      else
        format.html { render :new }
        format.json { render json: @price_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /price_entries/1
  # PATCH/PUT /price_entries/1.json
  def update
    respond_to do |format|
      if @price_entry.update(price_entry_params)
        format.html { redirect_to @price_entry, notice: 'Price entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @price_entry }
      else
        format.html { render :edit }
        format.json { render json: @price_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /price_entries/1
  # DELETE /price_entries/1.json
  def destroy
    @price_entry.destroy
    respond_to do |format|
      format.html { redirect_to price_entries_url, notice: 'Price entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price_entry
      @price_entry = PriceEntry.find(params[:id])
    end

    def set_footer
      @next = ""
      @previous = "packages"
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def price_entry_params
      params.require(:price_entry).permit(:package_id, :distributor_id, :price, :expiration_date, :sale_type_id)
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :multiplier)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/price_entries_helper.rb
module PriceEntriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sale_types_helper.rb
module SaleTypesHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/price_entries/_form.html.erb
<%= form_with(model: price_entry, local: true) do |form| %>
  <% if price_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price_entry.errors.count, "error") %> prohibited this price_entry from being saved:</h2>

      <ul>
      <% price_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :package_id %>
    <%= form.select(:package_id, @package)%>    
  </div>


  <div class="field">
    <%= form.label :distributor_id %>
    <%= form.select(:distributor_id, @distributor)%>    
  </div>



  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :price_entry_price %>
  </div>

  <div class="field">
    <%= form.label :sale_type_id %>
    <%= form.select(:sale_type_id, @sale_type)%>    
  </div>



  <div class="field">
    <%= form.label :expiration_date %>
    <%= form.date_select :expiration_date, id: :price_entry_expiration_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/price_entries/edit.html.erb
<h1>Editing Price Entry</h1>

<%= render 'form', price_entry: @price_entry %>

<%= link_to 'Show', @price_entry %> |
<%= link_to 'Back', price_entries_path %>

app/views/price_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Price Entries</h1>

<table>
  <thead>
    <tr>
      <th>Supplier</th>
      <th>Product</th>
      <th>Package</th>
      <th>Size</th>
      <th>Units</th>
      <th>Distributor</th>
      <th>Price</th>
      <th>Sale Type</th>
      <th>Expiration Date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @price_entries.each do |price_entry| %>
      <tr>
        <td><%= price_entry.package.product.supplier.name %></td>
        <td><%= price_entry.package.product.name %></td>
        <td><%= link_to price_entry.package.pkgsize, package_path(price_entry.package.id) %></td>
        <td><%= link_to price_entry.package.size, package_path(price_entry.package.id) %></td>
        <td><%= link_to price_entry.package.unit.name, package_path(price_entry.package.id)  %></td>
        <td><%= price_entry.distributor.name %></td>
        <td><%= price_entry.price %></td>
        <td><%= price_entry.sale_type.name %></td>
        <td><%= price_entry.expiration_date %></td>
        <td><%= price_entry.user.email %></td>
        <td><%= link_to 'showshow', price_entry %></td>
        <td><%= link_to 'Edit', edit_price_entry_path(price_entry) %></td>
        <td><%= link_to 'Destroy', price_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price Entry', new_price_entry_path %>

app/views/price_entries/new.html.erb
<h1>New Price Entry</h1>

<%= render 'form', price_entry: @price_entry %>

<%= link_to 'Back', price_entries_path %>

app/views/price_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Package:</strong>
  <%= @price_entry.package_id %>
</p>

<p>
  <strong>Distributor:</strong>
  <%= @price_entry.distributor_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @price_entry.price %>
</p>

<p>
  <strong>Date expirate:</strong>
  <%= @price_entry.expiration_date %>
</p>











<%= link_to 'Edit', edit_price_entry_path(@price_entry) %> |
<%= link_to 'Back', price_entries_path %>