config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :sale_types
  resources :price_entries
  resources :distributors
  resources :sub_categories
  resources :packages
  resources :units
  resources :categories
  resources :products
  resources :suppliers


  root to: 'products#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
	has_many :sub_categories, dependent: :destroy
end

app/models/distributor.rb
class Distributor < ApplicationRecord

	has_many :price_entries, dependent: :destroy
	
end

app/models/package.rb
class Package < ApplicationRecord

	belongs_to :product
	belongs_to :unit

	has_many :price_entries, dependent: :destroy

end

app/models/price_entry.rb
class PriceEntry < ApplicationRecord

	belongs_to :distributor
	belongs_to :package
	belongs_to :sale_type
	belongs_to :user


end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :supplier
	belongs_to :category 
	belongs_to :sub_category 

	has_many :packages, dependent: :destroy

	validates :name, uniqueness: { case_sensitive: false}
	validates :name, presence: true

	validates :category_id, presence: true
	validates :sub_category_id, presence: true


	
end

app/models/sale_type.rb
class SaleType < ApplicationRecord
	has_many :price_entries, dependent: :destroy

end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
	has_many :products, dependent: :destroy

	belongs_to :category
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :products, dependent: :destroy

	validates :name, uniqueness: { case_sensitive: false}
	validates :name, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
	has_many :packages , dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :price_entries
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = SubCategory.all
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @categories = Category.all.map { |i| [i.name, i.id]}.sort
    @sub_category = SubCategory.new

  end

  # GET /sub_categories/1/edit
  def edit
    @categories = Category.all.map { |i| [i.name, i.id]}.sort
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_category_params
      params.require(:sub_category).permit(:name, :category_id)
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :multiplier)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/price_entries_helper.rb
module PriceEntriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sale_types_helper.rb
module SaleTypesHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/sub_categories/_form.html.erb
<%= form_with(model: sub_category, local: true) do |form| %>
  <% if sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
      <% sub_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :category %>
    <%= form.select(:category_id, @categories)%>    
    <%= link_to new_category_path do%>
            <span class="fa fa-plus"> Category</span>
          <% end %>
  </div>



  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :sub_category_name %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_categories/edit.html.erb
<h1>Editing Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Show', @sub_category %> |
<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.name %></td>
        <td><%= sub_category.category.name %></td>
        <td><%= link_to 'Show', sub_category %></td>
        <td><%= link_to 'Edit', edit_sub_category_path(sub_category) %></td>
        <td><%= link_to 'Destroy', sub_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub Category', new_sub_category_path %>

app/views/sub_categories/new.html.erb
<h1>New Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sub_category.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @sub_category.category.name %>
</p>

<%= link_to 'Edit', edit_sub_category_path(@sub_category) %> |
<%= link_to 'Back', sub_categories_path %>