config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :sale_types
  resources :price_entries
  resources :distributors
  resources :sub_categories
  resources :packages
  resources :units
  resources :categories
  resources :products
  resources :suppliers


  root to: 'products#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
	has_many :sub_categories, dependent: :destroy
end

app/models/distributor.rb
class Distributor < ApplicationRecord

	has_many :price_entries, dependent: :destroy
	
end

app/models/package.rb
class Package < ApplicationRecord

	belongs_to :product
	belongs_to :unit

	has_many :price_entries, dependent: :destroy

end

app/models/price_entry.rb
class PriceEntry < ApplicationRecord

	belongs_to :distributor
	belongs_to :package
	belongs_to :sale_type
	belongs_to :user


end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :supplier
	belongs_to :category 
	belongs_to :sub_category 

	has_many :packages, dependent: :destroy

	validates :name, uniqueness: { case_sensitive: false}
	validates :name, presence: true

	validates :category_id, presence: true
	validates :sub_category_id, presence: true


	
end

app/models/sale_type.rb
class SaleType < ApplicationRecord
	has_many :price_entries, dependent: :destroy

end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
	has_many :products, dependent: :destroy

	belongs_to :category
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :products, dependent: :destroy

	validates :name, uniqueness: { case_sensitive: false}
	validates :name, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
	has_many :packages , dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :price_entries
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_footer

  # GET /products
  # GET /products.json
  def index
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct:true)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    packages = Package.all
    @package_select = @product.packages
  end

  # GET /products/new
  def new
    @product = Product.new
    @supplier = Supplier.all.map { |i| [i.name, i.id]}
    @category = Category.all.map { |i| [i.name, i.id]}.sort
    @sub_category = SubCategory.all.map { |i| [i.name, i.id]}.sort
  end

  # GET /products/1/edit
  def edit
    @supplier = Supplier.all.map { |i| [i.name, i.id]}
    @category = Category.all.map { |i| [i.name, i.id]}.sort
    @sub_category = SubCategory.all.map { |i| [i.name, i.id]}.sort
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_footer
      @next = "packages"
      @previous = "suppliers"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:supplier_id, :name, :category_id, :sub_category_id, :q)
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :multiplier)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/price_entries_helper.rb
module PriceEntriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sale_types_helper.rb
module SaleTypesHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>

  </div>


  <div class="field">
    <%= form.label :supplier %>
    <%= form.select(:supplier_id, @supplier)%>    
    <%= link_to new_supplier_path do%>
            <span class="fa fa-plus"> Supplier</span>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select(:category_id, @category)%>    
  
  </div>
  <div class="field">
    <%= form.label :sub_category %>
    <%= form.select(:sub_category_id, @sub_category)%>    
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>




<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=link_to "Products", products_path %> </h1>


<%= search_form_for @q do |f| %>

  
  <%= f.search_field :name_or_supplier_name_or_category_name_cont %>

  <%= f.submit %>
<% end %>

<br>

<table>
  <thead>
    <tr>
      <th><%= sort_link(@q, :name, default_order: :desc) %></th>
      <th>Supplier</th>
      <th>Category</th>
      <th>SubCategory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product %></td>
        <td><%= link_to product.supplier.name, supplier_path(product.supplier_id) %></td>
        <td><%= product.category.name %></td>
        <td><%= product.sub_category.name %></td>
       <td><%= link_to edit_product_path(product) do%>
            <span class="fa fa-edit"></span>
          <% end %>
          </td>
        <td><%= link_to product, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="fa fa-trash"></span>


          <% end %>
        </td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_product_path do%>
            <span class="fa fa-plus"> Product</span>
          <% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>


  <div>    
    <%= link_to new_package_path do%>
            <span class="fa fa-plus"> Package</span>
    <% end %>
  </div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Supplier:</strong>
  <%= @product.supplier.name %>
</p>

<p>
  <strong>Product Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.name %>  /  
  <strong>SubCategory:</strong>
  <%= @product.sub_category.name %>
</p>







<table>
  <thead>
    <tr>
      <th>Package</th>
      <th>Barcode</th>
      <th>Pkgsize</th>
      <th>Size</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @package_select.each do |package_select| %>
      <tr>
        <td><%= package_select.product.name %></td>
        <td><%= package_select.barcode %></td>
        <td><%= package_select.pkgsize %></td>
        <td><%= package_select.size %></td>
        <td><%= package_select.unit.name  %></td>
      </tr>
    <% end %>
  </tbody>
</table>





  <div>    
    <%= link_to new_package_path do%>
            <span class="fa fa-plus"> Package</span>
    <% end %>
  </div>