config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :sale_types
  resources :price_entries
  resources :distributors
  resources :sub_categories
  resources :packages
  resources :units
  resources :categories
  resources :products
  resources :suppliers


  root to: 'products#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products, dependent: :destroy
	has_many :sub_categories, dependent: :destroy
end

app/models/distributor.rb
class Distributor < ApplicationRecord

	has_many :price_entries, dependent: :destroy
	
end

app/models/package.rb
class Package < ApplicationRecord

	belongs_to :product
	belongs_to :unit

	has_many :price_entries, dependent: :destroy

end

app/models/price_entry.rb
class PriceEntry < ApplicationRecord

	belongs_to :distributor
	belongs_to :package
	belongs_to :sale_type
	belongs_to :user


end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :supplier
	belongs_to :category 
	belongs_to :sub_category 

	has_many :packages, dependent: :destroy

	validates :name, uniqueness: { case_sensitive: false}
	validates :name, presence: true

	validates :category_id, presence: true
	validates :sub_category_id, presence: true


	
end

app/models/sale_type.rb
class SaleType < ApplicationRecord
	has_many :price_entries, dependent: :destroy

end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
	has_many :products, dependent: :destroy

	belongs_to :category
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :products, dependent: :destroy

	validates :name, uniqueness: { case_sensitive: false}
	validates :name, presence: true
end

app/models/unit.rb
class Unit < ApplicationRecord
	has_many :packages , dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :price_entries
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :multiplier)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sale_types_helper.rb
module SaleTypesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">


  	<%if !@previous.blank? %>
			<p><i class="fas fa-angle-double-left"></i></i> <%= link_to @previous.capitalize, @previous %> <i class="fas fa-angle-double-left"></i></p>

		<% else %>
			<p></p>		


		<% end %>

    <%if !@next.blank? %>

   		<p><i class="fas fa-angle-double-right"></i> <%= link_to @next.capitalize, @next %> <i class="fas fa-angle-double-right"></i></p>

    <% end %>







</div>



</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "KOMOdt", products_path, class: "navbar-brand", id: "logo" %>
    </div>




	<% if current_user.present? %>

		<div class="navbar-header">
		  <%= link_to "PriceEntries", price_entries_path, class: "navbar-brand", id: "logo" %>
		</div>



		<div class="dropdown">
		  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		    Add
		  </button>
		  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
		  	<%= link_to "Supplier", suppliers_path , class: "dropdown-item" %>
		  	<%= link_to "Product", products_path , class: "dropdown-item" %>
		  	<%= link_to "Package", packages_path , class: "dropdown-item" %>
		  </div>
		</div>


		<div class="dropdown">
		  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		    Misc
		  </button>
		  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
		  	<%= link_to "Categories", categories_path , class: "dropdown-item" %>
		  	<%= link_to "SubCategories", sub_categories_path , class: "dropdown-item" %>
		  	<%= link_to "Units", units_path , class: "dropdown-item" %>
		  	<%= link_to "Distributors", distributors_path , class: "dropdown-item" %>
		  	<%= link_to "SalesType", sale_types_path , class: "dropdown-item" %>
		  </div>
		</div>

		<div>
			<ul class="navbar-nav mr-auto">
			  <li class="nav-item">
			    <a class="nav-link">
			      <%= link_to edit_user_registration_path(current_user) do %>
			          <i class="fas fa-user"></i> Profile
			      <% end %>
			    </a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link">
			      <%= link_to destroy_user_session_path, method: :delete do %>
			          <i class="fas fa-sign-out-alt "></i> Signout
			      <% end %>
			    </a>
			  </li>
			</ul>
		</div>

	<% else %>

		<div>
			<ul class="navbar-nav mr-auto">
			  <li class="nav-item">
			    <a class="nav-link">
			      <%= link_to new_user_session_path do %>
			          <i class="fas fa-user"></i> Signin
			      <% end %>
			    </a>
			</ul>
		</div>


	<% end %>

	</div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Komodt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">


    
  </head>

  <body>

  	<%= render 'layouts/navigation' %>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


	  <div class="jumbotron">		


      <div class="container">
        <div class="row">
          <div class="col-sm">


          </div>
          <div class="col-sm">
            <%= yield %>
          </div>
          <div class="col-sm">


          </div>
        </div>
      </div>

	  </div>


    <%= render 'layouts/footer' %>



  </body>
</html>